# Generated by Django 3.2.6 on 2021-08-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caketype', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('cakeimage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('custreview', models.CharField(max_length=400)),
            ],
        ),
    ]
