# Generated by Django 3.2.6 on 2021-08-15 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakelust', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reviews',
            new_name='Review',
        ),
    ]
