# Generated by Django 3.2.6 on 2021-08-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakelust', '0002_rename_reviews_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='cakeimage',
            field=models.ImageField(upload_to='static'),
        ),
    ]
