# Generated by Django 3.2.6 on 2021-08-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakelust', '0003_alter_gallery_cakeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='cakeimage',
            field=models.ImageField(upload_to='media'),
        ),
    ]
