# Generated by Django 3.2.6 on 2021-08-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakelust', '0004_alter_gallery_cakeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='email',
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
