# Generated by Django 3.2.6 on 2021-08-15 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakelust', '0007_remove_gallery_cakedesc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='cakeprice',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='cakesize',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='cakename',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cakelust.cake'),
        ),
        migrations.CreateModel(
            name='Cakesetprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cakedesc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cakedesc', to='cakelust.cake')),
                ('cakename', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cakename', to='cakelust.cake')),
                ('cakeprice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cakelust.priceguide')),
                ('cakesize', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cakelust.cakesize')),
            ],
        ),
    ]
