# Generated by Django 3.2.6 on 2021-08-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakelust', '0008_auto_20210815_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cakesetprice',
            name='cakedesc',
        ),
    ]
