# Generated by Django 3.2.6 on 2021-08-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakelust', '0009_remove_cakesetprice_cakedesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='viewcake',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
