# Generated by Django 3.2.6 on 2021-08-15 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakelust', '0010_cake_viewcake'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='cakeprice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cakelust.priceguide'),
        ),
        migrations.AddField(
            model_name='cake',
            name='cakesize',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cakelust.cakesize'),
        ),
        migrations.DeleteModel(
            name='Cakesetprice',
        ),
    ]
