# Generated by Django 3.2.6 on 2021-08-15 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakelust', '0011_auto_20210815_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='cakeprice',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='cakesize',
        ),
        migrations.DeleteModel(
            name='Cakesize',
        ),
        migrations.DeleteModel(
            name='Priceguide',
        ),
    ]
