# Generated by Django 3.2.6 on 2021-08-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakelust', '0012_auto_20210815_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricelist', models.ImageField(upload_to='media')),
            ],
        ),
    ]
